# Server port
server:
  port: 8070

spring:
  application:
    name: wallet

  # Configuración de la base de datos
  datasource:
    url: jdbc:sqlserver://test.cdiaysuewfbl.us-east-2.rds.amazonaws.com:1433;databaseName=wallet;currentSchema=wallet;encrypt=false;trustServerCertificate=true
    username: admin
    password: 19950323.*Test
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # JPA Configuration
  jpa:
    open-in-view: 'true'
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'false'

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
